/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface TokenSwapInterface extends utils.Interface {
  functions: {
    "DAI()": FunctionFragment;
    "USDC()": FunctionFragment;
    "WETH9()": FunctionFragment;
    "poolFee()": FunctionFragment;
    "swapExactInputMultihop(uint256)": FunctionFragment;
    "swapExactInputSingle(address,address,uint256)": FunctionFragment;
    "swapExactOutputMultihop(uint256,uint256)": FunctionFragment;
    "swapExactOutputSingle(uint256,uint256)": FunctionFragment;
    "swapRouter()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DAI"
      | "USDC"
      | "WETH9"
      | "poolFee"
      | "swapExactInputMultihop"
      | "swapExactInputSingle"
      | "swapExactOutputMultihop"
      | "swapExactOutputSingle"
      | "swapRouter"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "DAI", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "WETH9", values?: undefined): string;
  encodeFunctionData(functionFragment: "poolFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapExactInputMultihop",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactInputSingle",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactOutputMultihop",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactOutputSingle",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "DAI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WETH9", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapExactInputMultihop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactInputSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactOutputMultihop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactOutputSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;

  events: {
    "swapExactInputMultihopEvent(uint256)": EventFragment;
    "swapExactInputSingleEvent(uint256)": EventFragment;
    "swapExactOutputMultihopEvent(uint256)": EventFragment;
    "swapExactOutputSingleEvent(uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "swapExactInputMultihopEvent"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "swapExactInputSingleEvent"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "swapExactOutputMultihopEvent"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "swapExactOutputSingleEvent"): EventFragment;
}

export interface swapExactInputMultihopEventEventObject {
  amountOut: BigNumber;
}
export type swapExactInputMultihopEventEvent = TypedEvent<
  [BigNumber],
  swapExactInputMultihopEventEventObject
>;

export type swapExactInputMultihopEventEventFilter =
  TypedEventFilter<swapExactInputMultihopEventEvent>;

export interface swapExactInputSingleEventEventObject {
  amountOut: BigNumber;
}
export type swapExactInputSingleEventEvent = TypedEvent<
  [BigNumber],
  swapExactInputSingleEventEventObject
>;

export type swapExactInputSingleEventEventFilter =
  TypedEventFilter<swapExactInputSingleEventEvent>;

export interface swapExactOutputMultihopEventEventObject {
  amountIn: BigNumber;
}
export type swapExactOutputMultihopEventEvent = TypedEvent<
  [BigNumber],
  swapExactOutputMultihopEventEventObject
>;

export type swapExactOutputMultihopEventEventFilter =
  TypedEventFilter<swapExactOutputMultihopEventEvent>;

export interface swapExactOutputSingleEventEventObject {
  amountIn: BigNumber;
}
export type swapExactOutputSingleEventEvent = TypedEvent<
  [BigNumber],
  swapExactOutputSingleEventEventObject
>;

export type swapExactOutputSingleEventEventFilter =
  TypedEventFilter<swapExactOutputSingleEventEvent>;

export interface TokenSwap extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TokenSwapInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DAI(overrides?: CallOverrides): Promise<[string]>;

    USDC(overrides?: CallOverrides): Promise<[string]>;

    WETH9(overrides?: CallOverrides): Promise<[string]>;

    poolFee(overrides?: CallOverrides): Promise<[number]>;

    swapExactInputMultihop(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapExactInputSingle(
      token1: PromiseOrValue<string>,
      token2: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapExactOutputMultihop(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapExactOutputSingle(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<[string]>;
  };

  DAI(overrides?: CallOverrides): Promise<string>;

  USDC(overrides?: CallOverrides): Promise<string>;

  WETH9(overrides?: CallOverrides): Promise<string>;

  poolFee(overrides?: CallOverrides): Promise<number>;

  swapExactInputMultihop(
    amountIn: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapExactInputSingle(
    token1: PromiseOrValue<string>,
    token2: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapExactOutputMultihop(
    amountOut: PromiseOrValue<BigNumberish>,
    amountInMaximum: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapExactOutputSingle(
    amountOut: PromiseOrValue<BigNumberish>,
    amountInMaximum: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapRouter(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    DAI(overrides?: CallOverrides): Promise<string>;

    USDC(overrides?: CallOverrides): Promise<string>;

    WETH9(overrides?: CallOverrides): Promise<string>;

    poolFee(overrides?: CallOverrides): Promise<number>;

    swapExactInputMultihop(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactInputSingle(
      token1: PromiseOrValue<string>,
      token2: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactOutputMultihop(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactOutputSingle(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "swapExactInputMultihopEvent(uint256)"(
      amountOut?: null
    ): swapExactInputMultihopEventEventFilter;
    swapExactInputMultihopEvent(
      amountOut?: null
    ): swapExactInputMultihopEventEventFilter;

    "swapExactInputSingleEvent(uint256)"(
      amountOut?: null
    ): swapExactInputSingleEventEventFilter;
    swapExactInputSingleEvent(
      amountOut?: null
    ): swapExactInputSingleEventEventFilter;

    "swapExactOutputMultihopEvent(uint256)"(
      amountIn?: null
    ): swapExactOutputMultihopEventEventFilter;
    swapExactOutputMultihopEvent(
      amountIn?: null
    ): swapExactOutputMultihopEventEventFilter;

    "swapExactOutputSingleEvent(uint256)"(
      amountIn?: null
    ): swapExactOutputSingleEventEventFilter;
    swapExactOutputSingleEvent(
      amountIn?: null
    ): swapExactOutputSingleEventEventFilter;
  };

  estimateGas: {
    DAI(overrides?: CallOverrides): Promise<BigNumber>;

    USDC(overrides?: CallOverrides): Promise<BigNumber>;

    WETH9(overrides?: CallOverrides): Promise<BigNumber>;

    poolFee(overrides?: CallOverrides): Promise<BigNumber>;

    swapExactInputMultihop(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapExactInputSingle(
      token1: PromiseOrValue<string>,
      token2: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapExactOutputMultihop(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapExactOutputSingle(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DAI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    USDC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WETH9(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapExactInputMultihop(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapExactInputSingle(
      token1: PromiseOrValue<string>,
      token2: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapExactOutputMultihop(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapExactOutputSingle(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
